//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{


    public partial class Conference
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox TextBox1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl name;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl venue;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dateStart;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dateEnd;
        protected global::System.Web.UI.WebControls.Label AttendResponse;
        protected global::System.Web.UI.WebControls.Label Result;
        protected global::System.Web.UI.WebControls.TextBox ReviewText;
        protected global::System.Web.UI.WebControls.Label ReviewResponse;




    }
}
